### ISSUE TITLE
compare

### ISSUE THREAD

**Issue by kylemac** [carrot/restful-api-spec#7]
http://jsonapi.org/

**Comment by BrandonRomano** [comment]
Going to close this out -- there's quite a bit in json api's spec that I disagree with (just ran through it more specifically).

JSON API trades way too much fluency of an API out for standardization (and I don't particularly agree with all of the standardization).  json api very much seems like an all-or-nothing decision, and accepting all of it is definitely out of question as we lose out on a lot of nice things that our relatively loose spec allows.
