### ISSUE TITLE
Not sure if you're interested, but made a node function for interfaces

### ISSUE THREAD

**Issue by corysimmons** [carrot/restful-api-spec#9]
https://github.com/corysimmons/status-interfaces

Helps me. Dunno if you guys have something like this (or better) or if it's all done on Go side, but maybe it'll be helpful.

ofc, feel free to close this whenever

**Comment by BrandonRomano** [comment]
Thanks for the share, this looks very similar to something that we've written in Go:

https://github.com/go-carrot/response

We write a lot of our APIs in Go, but we still do use Javascript.

This library I shared actually follows the base interface we've proposed in #8.  So technically is future-spec for this repo.

**Comment by corysimmons** [comment]
Ah, nice, I'm glad I pinged you Brandon. I like wrapping all that cruft in meta as well. Will update my lib.
